import 'package:flutter/material.dart';

void main() {
  runApp(const shuhomepage());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class shuhomepage extends StatelessWidget {
  const shuhomepage({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
        ]),
      ),
    );
  }
}

class extendstelessWidget {
  @override
  Widget build (BuildContext context) {
    return Column(
      children: [
        Container(
          width: 406,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFF9ED6FF)),
          child: Stack(
            children: [
              Positioned(
                left: 347,
                top: 30,
                child: Container(
                  width: 46,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: OvalBorder(
                      side: BorderSide(width: 1, color: Colors.white),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x66000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 8,
                top: 30,
                child: Container(
                  width: 46,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: OvalBorder(
                      side: BorderSide(width: 1, color: Colors.white),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x66000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 39,
                child: Container(
                  width: 29,
                  height: 21,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/29x21"),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(159.50),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 357,
                top: 39,
                child: Container(
                  width: 27,
                  height: 21,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/27x21"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 83,
                child: Container(
                  width: 312,
                  height: 43,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(35),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 59,
                top: 94,
                child: SizedBox(
                  width: 247,
                  height: 25,
                  child: Text(
                    'What would you like to have?',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF868383),
                      fontSize: 16,
                      fontFamily: 'Abhaya Libre Medium',
                      fontWeight: FontWeight.w500,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 58,
                top: 88,
                child: Container(
                  width: 29,
                  height: 38,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 29,
                          height: 38,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/29x38"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: -17.10,
                        top: -29.94,
                        child: Container(
                          width: 195.56,
                          height: 307.45,
                          decoration: BoxDecoration(color: Color(0xFF24BAEC)),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -10,
                top: 159,
                child: SizedBox(
                  width: 102,
                  height: 31,
                  child: Text(
                    'Categories',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Abhaya Libre Medium',
                      fontWeight: FontWeight.w500,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -19,
                top: 282,
                child: SizedBox(
                  width: 102,
                  height: 31,
                  child: Text(
                    'Popular',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Abhaya Libre Medium',
                      fontWeight: FontWeight.w500,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -21,
                top: 552,
                child: SizedBox(
                  width: 102,
                  height: 31,
                  child: Text(
                    'Newest',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Abhaya Libre Medium',
                      fontWeight: FontWeight.w500,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -50,
                top: 193,
                child: Container(
                  padding: const EdgeInsets.only(right: 100),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        height: 49,
                        padding: const EdgeInsets.symmetric(horizontal: 56),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: 55,
                              height: 49,
                              decoration: ShapeDecoration(
                                color: Color(0xFF24BAEC),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x3F000000),
                                    blurRadius: 4,
                                    offset: Offset(0, 4),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                            ),
                            const SizedBox(width: 23),
                            Container(
                              width: 42,
                              height: 42,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/42x42"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            const SizedBox(width: 23),
                            Container(
                              width: 55,
                              height: 49,
                              decoration: ShapeDecoration(
                                color: Color(0xFF24BAEC),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x3F000000),
                                    blurRadius: 4,
                                    offset: Offset(0, 4),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                            ),
                            const SizedBox(width: 23),
                            Container(
                              width: 40,
                              height: 39,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/40x39"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            const SizedBox(width: 23),
                            Container(
                              width: 55,
                              height: 49,
                              decoration: ShapeDecoration(
                                color: Color(0xFF24BAEC),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x3F000000),
                                    blurRadius: 4,
                                    offset: Offset(0, 4),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                            ),
                            const SizedBox(width: 23),
                            Container(
                              width: 29,
                              height: 43,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/29x43"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            const SizedBox(width: 23),
                            Container(
                              width: 55,
                              height: 49,
                              decoration: ShapeDecoration(
                                color: Color(0xFF24BAEC),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x3F000000),
                                    blurRadius: 4,
                                    offset: Offset(0, 4),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                            ),
                            const SizedBox(width: 23),
                            Container(
                              width: 29,
                              height: 36,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/29x36"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            const SizedBox(width: 23),
                            Container(
                              width: 55,
                              height: 49,
                              decoration: ShapeDecoration(
                                color: Color(0xFF24BAEC),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x3F000000),
                                    blurRadius: 4,
                                    offset: Offset(0, 4),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                            ),
                            const SizedBox(width: 23),
                            Container(
                              width: 32,
                              height: 38,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/32x38"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            const SizedBox(width: 23),
                            Container(
                              width: 55,
                              height: 49,
                              decoration: ShapeDecoration(
                                color: Color(0xFF24BAEC),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x3F000000),
                                    blurRadius: 4,
                                    offset: Offset(0, 4),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                            ),
                            const SizedBox(width: 23),
                            Container(
                              width: 49,
                              height: 39,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/49x39"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -19,
                top: 313,
                child: Container(
                  width: 425,
                  height: 192,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 34,
                        top: 0,
                        child: Container(
                          width: 152,
                          height: 192,
                          decoration: ShapeDecoration(
                            color: Color(0xFF24BAEC),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 209,
                        top: 0,
                        child: Container(
                          width: 152,
                          height: 192,
                          decoration: ShapeDecoration(
                            color: Color(0xFF24BAEC),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 384,
                        top: 0,
                        child: Container(
                          width: 152,
                          height: 192,
                          decoration: ShapeDecoration(
                            color: Color(0xFF24BAEC),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 559,
                        top: 0,
                        child: Container(
                          width: 152,
                          height: 192,
                          decoration: ShapeDecoration(
                            color: Color(0xFF24BAEC),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 42,
                        top: 130,
                        child: SizedBox(
                          width: 136,
                          height: 54,
                          child: Text(
                            'Original Bubble Milk Tea',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 13,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.14,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 209,
                        top: 130,
                        child: SizedBox(
                          width: 136,
                          height: 54,
                          child: Text(
                            'Original French Fries',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 13,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.14,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 384,
                        top: 130,
                        child: SizedBox(
                          width: 136,
                          height: 54,
                          child: Text(
                            'Chocolate MilkShake',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 13,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.14,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 536,
                        top: 130,
                        child: SizedBox(
                          width: 136,
                          height: 54,
                          child: Text(
                            'Orange Juice',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 13,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.14,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 157,
                        child: SizedBox(
                          width: 136,
                          height: 30,
                          child: Text(
                            'Rp.45.000',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 13,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.14,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 178,
                        top: 157,
                        child: SizedBox(
                          width: 136,
                          height: 30,
                          child: Text(
                            'Rp.35.000',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 13,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.14,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 353,
                        top: 157,
                        child: SizedBox(
                          width: 136,
                          height: 30,
                          child: Text(
                            'Rp.55.000',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 13,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.14,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 528,
                        top: 157,
                        child: SizedBox(
                          width: 136,
                          height: 30,
                          child: Text(
                            'Rp.50.000',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 13,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.14,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 60,
                        top: 6,
                        child: Container(
                          width: 100,
                          height: 131,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/100x131"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 384,
                        top: 0,
                        child: Container(
                          width: 152,
                          height: 151,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/152x151"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 560,
                        top: 1,
                        child: Container(
                          width: 152,
                          height: 136,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/152x136"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 219,
                        top: 16,
                        child: Container(
                          width: 129,
                          height: 119,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/129x119"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 583,
                child: Container(
                  width: 370,
                  height: 267,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 370,
                          height: 137,
                          decoration: ShapeDecoration(
                            color: Color(0xFF24BAEC),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 346,
                        child: Container(
                          width: 370,
                          height: 137,
                          decoration: ShapeDecoration(
                            color: Color(0xFF24BAEC),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 173,
                        child: Container(
                          width: 370,
                          height: 137,
                          decoration: ShapeDecoration(
                            color: Color(0xFF24BAEC),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 25,
                        top: 9,
                        child: Container(
                          width: 85,
                          height: 120,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/85x120"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 105,
                        top: 12,
                        child: SizedBox(
                          width: 211,
                          child: Text(
                            'Strawberry Milk Tea',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.06,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 74,
                        top: 184,
                        child: SizedBox(
                          width: 211,
                          child: Text(
                            'Avocado Juice',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.06,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 100,
                        top: 358,
                        child: SizedBox(
                          width: 211,
                          child: Text(
                            'Corndog Mozarella',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.06,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 127,
                        top: 69,
                        child: SizedBox(
                          width: 177,
                          height: 22,
                          child: Text(
                            'Taste Our Strawberry Milk Tea. We Provide Our Great Foods',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 122,
                        top: 242,
                        child: SizedBox(
                          width: 177,
                          height: 22,
                          child: Text(
                            'Taste Our Avocado Juice. We Provide Our Great Foods',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 127,
                        top: 415,
                        child: SizedBox(
                          width: 177,
                          height: 22,
                          child: Text(
                            'Taste Our Corndog Mozarella. We Provide Our Great Foods',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 127,
                        top: 415,
                        child: SizedBox(
                          width: 177,
                          height: 22,
                          child: Text(
                            'Taste Our Corndog Mozarella. We Provide Our Great Foods',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Abhaya Libre Medium',
                              fontWeight: FontWeight.w500,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 331,
                        top: 3,
                        child: Container(
                          width: 27,
                          height: 41,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/27x41"),
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 331,
                        top: 175,
                        child: Container(
                          width: 27,
                          height: 41,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/27x41"),
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 331,
                        top: 349,
                        child: Container(
                          width: 27,
                          height: 41,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/27x41"),
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 2,
                        top: 348,
                        child: Container(
                          width: 120,
                          height: 135,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/120x135"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: -6,
                        top: 175,
                        child: Container(
                          width: 122,
                          height: 141,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/122x141"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}