import 'package:flutter/material.dart';

void main() {
  runApp(const Dessert());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Dessert extends StatelessWidget {
  const Dessert({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          DessertOption(),
        ]),
      ),
    );
  }
}

class DessertOption extends StatelessWidget {
  const DessertOption({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(color: Color(0xFFCFEBFF)),
          child: Stack(
            children: [
              Positioned(
                left: 19,
                top: 178,
                child: Container(
                  width: 169,
                  height: 200,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF9ED6FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 401,
                child: Container(
                  width: 169,
                  height: 200,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF9ED6FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 204,
                top: 624,
                child: Container(
                  width: 169,
                  height: 200,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF9ED6FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 172,
                top: 790,
                child: SizedBox(
                  width: 231,
                  height: 34,
                  child: Text(
                    'Rp.45.000',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF001A3E),
                      fontSize: 16,
                      fontFamily: 'Averia Gruesa Libre',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 624,
                child: Container(
                  width: 169,
                  height: 200,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF9ED6FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: -12,
                top: 790,
                child: SizedBox(
                  width: 231,
                  height: 34,
                  child: Text(
                    'Rp.45.000',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF001A3E),
                      fontSize: 16,
                      fontFamily: 'Averia Gruesa Libre',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 204,
                top: 401,
                child: Container(
                  width: 169,
                  height: 200,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF9ED6FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 172,
                top: 567,
                child: SizedBox(
                  width: 231,
                  height: 34,
                  child: Text(
                    'Rp.85.000',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF001A3E),
                      fontSize: 16,
                      fontFamily: 'Averia Gruesa Libre',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 204,
                top: 178,
                child: Container(
                  width: 169,
                  height: 200,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF9ED6FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: -12,
                top: 345,
                child: SizedBox(
                  width: 416,
                  height: 256,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 185,
                        top: 0,
                        child: SizedBox(
                          width: 231,
                          height: 34,
                          child: Text(
                            'Rp.75.000',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Gruesa Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 222,
                        child: SizedBox(
                          width: 231,
                          height: 34,
                          child: Text(
                            'Rp.35.000',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Gruesa Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const Positioned(
                left: -12,
                top: 188,
                child: SizedBox(
                  width: 231,
                  height: 190,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 231,
                          height: 34,
                          child: Text(
                            'Macaron Mix 6 pcs',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Gruesa Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 156,
                        child: SizedBox(
                          width: 231,
                          height: 34,
                          child: Text(
                            'Rp.105.000',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Gruesa Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const Positioned(
                left: 20,
                top: 407,
                child: SizedBox(
                  width: 367,
                  height: 49,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 171,
                          height: 49,
                          child: Text(
                            'Signature Doughnut',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Serif Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 169,
                        top: 1,
                        child: SizedBox(
                          width: 198,
                          height: 40,
                          child: Text(
                            'Mochi Mix 5 pcs',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Serif Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const Positioned(
                left: 18,
                top: 634,
                child: SizedBox(
                  width: 369,
                  height: 49,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 171,
                          height: 49,
                          child: Text(
                            'Mochi TangYuan',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Serif Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 171,
                        top: 0,
                        child: SizedBox(
                          width: 198,
                          height: 40,
                          child: Text(
                            'Strawberry Cheese \nCake Cup',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Serif Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const Positioned(
                left: 172,
                top: 188,
                child: SizedBox(
                  width: 231,
                  height: 42,
                  child: Text(
                    'Blueberries     \n  Cheese Cake',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF001A3E),
                      fontSize: 16,
                      fontFamily: 'Averia Serif Libre',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -18,
                top: -86,
                child: SizedBox(
                  width: 444,
                  height: 241,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 444,
                          height: 241,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF71BBE4),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(16),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 45,
                        top: 141,
                        child: SizedBox(
                          width: 44,
                          height: 44,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 44,
                                  height: 44,
                                  decoration: const ShapeDecoration(
                                    color: Color(0xFFF6F6F8),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 10,
                                top: 10,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: const BoxDecoration(),
                                  child: const FlutterLogo(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 329,
                top: 55,
                child: SizedBox(
                  width: 44,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 44,
                          height: 44,
                          decoration: const ShapeDecoration(
                            color: Color(0xFFF6F6F8),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 10,
                        top: 10,
                        child: Container(
                          width: 24,
                          height: 24,
                          clipBehavior: Clip.antiAlias,
                          decoration: const BoxDecoration(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 266,
                top: 27,
                child: Container(
                  width: 170,
                  height: 99,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/170x99"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 115,
                top: 61,
                child: SizedBox(
                  width: 179,
                  height: 56,
                  child: Text(
                    'DESSERT',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF060056),
                      fontSize: 48,
                      fontFamily: 'Charm',
                      fontWeight: FontWeight.w400,
                      height: 0.01,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 178,
                child: Container(
                  width: 178,
                  height: 200,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/178x200"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 196,
                top: 222,
                child: Container(
                  width: 180,
                  height: 139,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/180x139"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -14,
                top: 386,
                child: Container(
                  width: 235,
                  height: 230,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/235x230"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 177,
                top: 381,
                child: Container(
                  width: 223,
                  height: 235,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/223x235"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -11,
                top: 634,
                child: Container(
                  width: 228,
                  height: 193,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/228x193"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 209,
                top: 663,
                child: Container(
                  width: 168,
                  height: 145,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/168x145"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}