import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const Tea());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Tea extends StatelessWidget {
  const Tea({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          TeaOption(),
        ]),
      ),
    );
  }
}

class TeaOption extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFCFEBFF)),
          child: Stack(
            children: [
              Positioned(
                left: 19,
                top: 178,
                child: Container(
                  width: 169,
                  height: 200,
                  decoration: ShapeDecoration(
                    color: Color(0xFF9ED6FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 401,
                child: Container(
                  width: 169,
                  height: 200,
                  decoration: ShapeDecoration(
                    color: Color(0xFF9ED6FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 204,
                top: 624,
                child: Container(
                  width: 169,
                  height: 200,
                  decoration: ShapeDecoration(
                    color: Color(0xFF9ED6FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 172,
                top: 790,
                child: SizedBox(
                  width: 231,
                  height: 34,
                  child: Text(
                    'Rp.40.000',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF001A3E),
                      fontSize: 16,
                      fontFamily: 'Averia Gruesa Libre',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 624,
                child: Container(
                  width: 169,
                  height: 200,
                  decoration: ShapeDecoration(
                    color: Color(0xFF9ED6FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -12,
                top: 790,
                child: SizedBox(
                  width: 231,
                  height: 34,
                  child: Text(
                    'Rp.40.000',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF001A3E),
                      fontSize: 16,
                      fontFamily: 'Averia Gruesa Libre',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 204,
                top: 401,
                child: Container(
                  width: 169,
                  height: 200,
                  decoration: ShapeDecoration(
                    color: Color(0xFF9ED6FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 172,
                top: 567,
                child: SizedBox(
                  width: 231,
                  height: 34,
                  child: Text(
                    'Rp.55.000',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF001A3E),
                      fontSize: 16,
                      fontFamily: 'Averia Gruesa Libre',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 204,
                top: 178,
                child: Container(
                  width: 169,
                  height: 200,
                  decoration: ShapeDecoration(
                    color: Color(0xFF9ED6FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -12,
                top: 345,
                child: Container(
                  width: 416,
                  height: 256,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 185,
                        top: 0,
                        child: SizedBox(
                          width: 231,
                          height: 34,
                          child: Text(
                            'Rp.45.000',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Gruesa Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 222,
                        child: SizedBox(
                          width: 231,
                          height: 34,
                          child: Text(
                            'Rp.55.000',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Gruesa Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -12,
                top: 188,
                child: Container(
                  width: 231,
                  height: 190,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 231,
                          height: 34,
                          child: Text(
                            'Strawberry Bubble                             Milk Tea',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Gruesa Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 156,
                        child: SizedBox(
                          width: 231,
                          height: 34,
                          child: Text(
                            'Rp.65.000',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Gruesa Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 407,
                child: Container(
                  width: 367,
                  height: 49,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 171,
                          height: 49,
                          child: Text(
                            'Chocolate Bubble                             Milk Tea',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Serif Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 169,
                        top: 1,
                        child: SizedBox(
                          width: 198,
                          height: 40,
                          child: Text(
                            'Matcha Bubble                             Milk Tea',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Serif Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 634,
                child: Container(
                  width: 369,
                  height: 49,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 171,
                          height: 49,
                          child: Text(
                            'Ice Lemon Tea',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Serif Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 171,
                        top: 0,
                        child: SizedBox(
                          width: 198,
                          height: 40,
                          child: Text(
                            'Ice Jasmine Tea',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF001A3E),
                              fontSize: 16,
                              fontFamily: 'Averia Serif Libre',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 172,
                top: 188,
                child: SizedBox(
                  width: 231,
                  height: 42,
                  child: Text(
                    'Original Bubble                 Milk Tea',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF001A3E),
                      fontSize: 16,
                      fontFamily: 'Averia Serif Libre',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -18,
                top: -86,
                child: Container(
                  width: 444,
                  height: 241,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 444,
                          height: 241,
                          decoration: ShapeDecoration(
                            color: Color(0xFF71BBE4),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(16),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 45,
                        top: 141,
                        child: Container(
                          width: 44,
                          height: 44,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 44,
                                  height: 44,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFF6F6F8),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 10,
                                top: 10,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: FlutterLogo(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 329,
                top: 55,
                child: Container(
                  width: 44,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 44,
                          height: 44,
                          decoration: ShapeDecoration(
                            color: Color(0xFFF6F6F8),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 10,
                        top: 10,
                        child: Container(
                          width: 24,
                          height: 24,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 118,
                top: 61,
                child: SizedBox(
                  width: 157,
                  height: 56,
                  child: Text(
                    'TEA',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF060056),
                      fontSize: 64,
                      fontFamily: 'Charm',
                      fontWeight: FontWeight.w400,
                      height: 0.01,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 245,
                top: 450,
                child: Container(
                  width: 86,
                  height: 112,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/86x112"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 238,
                top: 212,
                child: Container(
                  width: 100,
                  height: 141,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/100x141"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 266,
                top: 27,
                child: Container(
                  width: 170,
                  height: 99,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/170x99"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 68,
                top: 230,
                child: Container(
                  width: 89,
                  height: 120,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/89x120"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 434,
                child: Container(
                  width: 151,
                  height: 151,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/151x151"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 642,
                child: Container(
                  width: 142,
                  height: 177,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/142x177"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 183,
                top: 606,
                child: Container(
                  width: 210,
                  height: 234,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/210x234"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}